config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:index, :show, :new, :create] do
    resources :votes, only: [:create]
    resources :answers, only: [:create] do
      resources :votes, only: [:create]
      resources :comments, only: [:create] do
      end
    end
    resources :comments, only: [:create] do
    resources :votes, only: [:create]
    end

  end

  resources :users, only: [:index, :create, :show]
  resource :sessions, only: [:create, :show, :test]

  get 'register' => 'users#new'
  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'
  root 'questions#index'

  get '/most_recent' => 'questions#most_recent'
  get '/popular' => 'questions#popular'
  get '/trending' => 'questions#trending'
  post '/makebest/:answer_id' => 'questions#make_best'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question, touch: true
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates :body, :user_id, :question_id, presence: true

  def vote_count
    ups = Vote.where(votable_id: self.id, votable_type: "Answer", value: 1).count
    downs = Vote.where(votable_id: self.id, votable_type: "Answer", value: -1).count
    return ups - downs
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true, touch: true
  belongs_to :user
  has_many :votes, as: :votable

  validates :user_id, :commentable_id, :commentable_type, :body, presence: true

  def vote_count
    ups = Vote.where(votable_id: self.id, votable_type: "Comment", value: 1).count
    downs = Vote.where(votable_id: self.id, votable_type: "Comment", value: -1).count
    return ups - downs
  end


end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates :title, :body, :user_id, presence: true


  def vote_count
    # self.votes.inject(0){||}
    # Consider refactoring - Devin has an idea
    ups = Vote.where(votable_id: self.id, votable_type: "Question", value: 1).count
    downs = Vote.where(votable_id: self.id, votable_type: "Question", value: -1).count
    return ups - downs
  end

  def self.sort_by_trending
    Question.all.includes(:user).order(updated_at: :desc)
  end

  def self.sort_by_recent
    Question.all.includes(:user).order(created_at: :desc)
  end

  def self.sort_by_votes
    Question.all.includes(:user).sort_by(&:vote_count).reverse
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes

  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true

  has_secure_password



  def questions_answered
    questions_answered = []
    self.answers.each do |ans|
      questions_answered << Question.find(ans.question_id)
    end
    return questions_answered.uniq
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :user_id, :votable_id, :votable_type, presence: true
  validates_uniqueness_of :user_id, scope: [:votable_id, :votable_type]
  validate :correct_value

  def correct_value
    unless self.value == 1 || self.value == -1
      errors.add(:value, "Invalid vote")
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create

    @answer = Answer.new(body: params[:answer][:body], question_id: params[:question_id], user_id: current_user.id)
    if @answer.save
      redirect_to :back
    else
      redirect_to :back
    end
  end

  # private
  # def answer_params
  #   params.require(:answer).permit(:body)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


   helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(body: params[:comment][:body], user_id: current_user.id)
    if params.include?(:answer_id)
      answer = Answer.find(params[:answer_id])
      comment.commentable = answer
    else
      question = Question.find(params[:question_id])
      comment.commentable = question
    end
    if comment.save
      redirect_to :back
    else
      redirect_to :back
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.includes(:user).order(created_at: :desc)
  end

  def trending
    @questions = Question.sort_by_trending
  end

  def most_recent
    @questions = Question.sort_by_recent
  end

  def popular
    @questions = Question.sort_by_votes
  end

  def show
    @question = Question.includes(:user, :answers, :comments).find(params[:id])
    if logged_in?
      if current_user.id == @question.user_id
        @my_question = true
      else
        @my_question = false
      end
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def make_best
    answer = Answer.find(params[:answer_id])
    question = Question.find(answer.question_id)
    question.update(best_answer_id: answer.id)
    redirect_to :back
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @user = User.new
      flash[:notice]=["Couldn't log you in."]
      render :new
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      @user = User.new
      flash[:notice] = user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end



  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    if params[:commit] == "^"
      val = 1
    else
      val = -1
    end
    vote = Vote.new(user_id: current_user.id, value: val)
    #probably split this to vote model
    if params.include?(:comment_id)
      comment = Comment.find(params[:comment_id])
      vote.votable = comment
    elsif params.include?(:answer_id)
      answer = Answer.find(params[:answer_id])
      vote.votable = answer
    else
      question = Question.find(params[:question_id])
      vote.votable = question
    end
    if vote.save
      redirect_to :back
    else
      redirect_to :back
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_downvote.html.erb
<%=form_for [@question, answer, Vote.new], html: {class: "downvote"} do |f| %>
  <%=f.submit "v", class: "button" %>
<%end%>

app/views/answers/_make_best.html.erb
<%if @my_question && answer.id != @question.best_answer_id%>
  <%= form_tag("/makebest/#{answer.id}", method: "post") do %>
  <%= submit_tag "Select as best Answer" %>
  <%end%>
<%end%>

<%if answer.id == @question.best_answer_id %>
<p>This has been selected as the best answer to this question. </p>
<%end%>

app/views/answers/_upvote.html.erb
<%=form_for [@question, answer, Vote.new], html: {class: "upvote"} do |f| %>
  <%=f.submit "^", class: "button" %>
<%end%>

app/views/comments/_downvote.html.erb
<%=form_for [@question, comment, Vote.new], html: {class: "downvote"} do |f| %>
  <%=f.submit "v", class: "button" %>
<%end%>

app/views/comments/_upvote.html.erb
<%=form_for [@question, comment, Vote.new], html: {class: "upvote"} do |f| %>
  <%=f.submit "^", class: "button" %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HaxxorzOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1> <%= link_to "Haxxorz Overflow", root_path%></h1>
    <h4 id = "user_auth">
      <%if logged_in?%>Logged in as <%=link_to current_user.username, current_user%> | <%end%>
      <% if logged_in? %>
        <%= link_to 'logout', logout_path %> | <%= link_to 'Ask a question', new_question_path %>
      <%else%>
        <%= link_to 'register', register_path %> | <%= link_to 'login', login_path %>
      <%end%>
    </h4>
  </header>
<% if flash[:notice] %>
    <div class="notice">
      <ul>
      <% flash[:notice].each do |notice| %>
      <li><%= notice %></li>
      <%end%>
    </ul>
    </div>
  <% end %>
<div id="content_container">
  <%= yield %>
</div>

</body>
</html>

app/views/questions/_downvote.html.erb
  <%= form_for [@question, Vote.new], html: {class: "downvote"} do |f| %>
    <%=f.submit "v", class: "button" %>
  <%end%>

app/views/questions/_question.html.erb
<li>
  <%= link_to question.title, question %> by <%= question.user.username %>
</li>

app/views/questions/_upvote.html.erb
  <%= form_for [@question, Vote.new], html: {class: "upvote"} do |f| %>
    <%=f.submit "^", class: "button" %>
  <%end%>

app/views/questions/index.html.erb
<ul>
  <%= render @questions %>
</ul>

app/views/questions/most_recent.html.erb
<nav>
  <%= link_to 'Trending', trending_path %> |
  <%= link_to 'Most Recent', most_recent_path %> |
  <%= link_to 'Most Popular', popular_path %>
</nav>

<ul>
  <%= render @questions %>
</ul>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit "Ask" %>
  </div>
<% end %>

app/views/questions/popular.html.erb
<nav>
  <%= link_to 'Trending', trending_path %> |
  <%= link_to 'Most Recent', most_recent_path %> |
  <%= link_to 'Most Popular', popular_path %>
</nav>

<ul>
  <%= render @questions %>
</ul>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>
<p>by <%= @question.user.username %></p>
<div class="big_vote_box"><span class="vote_box">
  <%= render partial: "upvote"%>
  <p><%=@question.vote_count%></p>
  <%= render partial: "downvote"%>
</span>
<span class="voted_on_box"><p><%= @question.body %></p></span></div>
<h4>Comments</h4>
<% @question.comments.each do |comment| %>
  <div class="big_vote_box"><span class="vote_box">
    <%= render partial: "/comments/upvote", locals: {comment: comment}%>
    <p><%=comment.vote_count%></p>
    <%= render partial: "/comments/downvote", locals: {comment: comment}%>
  </span>
  <span class="voted_on_box">
    <p><%= comment.body %> -<%= link_to comment.user.username, comment.user %></p>
  </span></div>
<% end %>

<% if logged_in? %>
  <h4>Add a comment</h4>
  <%= form_for [@question, Comment.new] do |f| %>
    <div>
      <%= f.text_area :body %>
    </div>
    <div>
      <%= f.submit "Comment" %>
    </div>
  <% end %>
<% end %>

<% @question.answers.each do |answer| %>
  <fieldset><legend><%= answer.user.username %></legend>
      <%= render partial: "/answers/make_best", locals: {answer: answer} %>
      <div class="big_vote_box"><span class="vote_box">
        <%= render partial: "/answers/upvote", locals: {answer: answer}%>
        <p><%=answer.vote_count%></p>
        <%= render partial: "/answers/downvote", locals: {answer: answer}%>
      </span>
    <span class="voted_on_box"><%= answer.body %></span></div>
    <% if answer.comments.length > 0 %>
      <h4>Comments:</h4>
    <% end %>
    <ul>
      <% answer.comments.each do |comment| %>
        <li>
      <div class="big_vote_box"><span class="vote_box">
        <%= render partial: "/comments/upvote", locals: {comment: comment}%>
          <p><%=comment.vote_count%></p>
        <%= render partial: "/comments/downvote", locals: {comment: comment}%>
      </span>
          <span class="voted_on_box">
            <%= comment.body %> - <%= link_to comment.user.username, comment.user %>
          </span></div>
        </li>
      <% end %>
    </ul>
    <% if logged_in? %>
      <%= form_for [@question, answer, Comment.new] do |f| %>
        <%= f.text_field :body %>
        <%= f.submit "Comment on this answer" %>
      <% end %>
    <% end %>
  </fieldset>
<% end %>

<% if logged_in? %>
  <h3>Answer this question</h3>
  <%= form_for [@question, Answer.new] do |f| %>
    <div>
      <%= f.text_area :body %>
    </div>
    <div>
      <%= f.submit "Answer" %>
    </div>
  <% end %>
<% end %>

app/views/questions/trending.html.erb
<nav>
  <%= link_to 'Trending', trending_path %> |
  <%= link_to 'Most Recent', most_recent_path %> |
  <%= link_to 'Most Popular', popular_path %>
</nav>

<ul>
  <%= render @questions %>
</ul>

app/views/users/new.html.erb
<h1>Sign up for Haxxorz Overflow</h1>
<%= form_for @user do |f| %>
  <p><%=f.label :email %>
  <%=f.text_field :email %></p>

  <p><%=f.label :username %>
  <%=f.text_field :username %></p>

  <p><%=f.label :password %>
  <%=f.password_field :password %></p>

  <p><%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %></p>

 <p> <%= f.submit "Become a Haxxor"%> </p>

<%end%>

app/views/users/show.html.erb
<h3>HaxxorName: <%= @user.username %></h3>

<img src="<%=@user.image_url%>">

<h4> Haxxor Questions:</h4>
 <%@user.questions.each do |question| %>
  <%= link_to question.title, question  %>
  <%end%>

<h4> Haxxor Questions Answered: </h4>
  <% @user.questions_answered.each do |question| %>
    <p><%= link_to question.title, question %></p>
  <%end%>